package upl

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
)

// Cookieを取得できる
func TestLogin(t *testing.T) {
	buf := &bytes.Buffer{}

	err := login(buf)
	if err != nil {
		t.Error(err)
	}

	expect := `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/	FALSE	0	filemanager	`
	assert.Contains(t, buf.String(), expect)
}

func TestParseCookie(t *testing.T) {
	input := `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/	FALSE	0	filemanager	dbf43855bb5bfc4a7fca5293ffa8da6b`
	cookie, err := parseCookie(input)
	if err != nil {
		t.Error(err)
	}
	assert.Equal(t, 32, len(cookie))

}
